services:
  react-counter:
    container_name: react-counter
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONTEXT: react-counter
    ports:
      - '58841:58841'
  shell:
    container_name: shell
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONTEXT: shell
    ports:
      - '62621:62621'
  shared-store:
    container_name: shared-store
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONTEXT: shared-store
    ports:
      - '55955:55955'
  vue-counter:
    container_name: vue-counter
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONTEXT: vue-counter
    ports:
      - '51997:51997'
